---
- hosts: ansible-moodle
  become: yes
  tasks:
    - name: Führe Apt Update aus.
      ansible.builtin.shell: |
        apt update &&
        apt upgrade -y &&
        apt clean
      register: log_update
    - name: Zeige mögliche Updates
      ansible.builtin.debug:
        var: log_update.stdout_lines 

        

  
