---
- hosts: ansible-moodle
  become: yes
  become_method: sudo
  tasks:
    - name: Führe Apt Update aus.
      ansible.builtin.shell: sudo apt update
      args:
        executable: /bin/bash
      register: log_update
    - name: Zeige mögliche Updates
      ansible.builtin.debug:
        var: log_update.stdout_lines 

        

  
