---
- name: Installiere Moodle.
  become: yes
  hosts: ansible-moodle # Ansible-Hosts (Ziel für die Erstellung + Download)
  tasks:
    - name: erstelle Datenbank.
      community.mysql.mysql_db:
        name: moodle
        state: present
        
