---
- hosts: ansible-moodle
  become: yes
  tasks:
    - name: Führe Apt Update aus.
      ansible.builtin.apt:
        update_cache: yes
        register: log_update
    - name: Zeige mögliche Updates
      ansible.builtin.debug:
        var: log_update.stdout_lines
    #- name: Installiere MariaDB.
    #  ansible.builtin.shell: |
    #    apt install mariadb-server &&
    #    apt install mariadb-client
    #- name: Installiere Apache2
    #  ansible.builtin.shell: apt install apache2 apache2-doc
    #- name: Aktiviere via a2enmod 
