---
- name: Installiere das Feature IIS.
  hosts: ansible-win
  become: yes
  tasks:
    - name: Rolle wird Installiert.
      ansible.windows.win_feature:
        name: Web-Server
        state: present
      
      
    
