---
- hosts: ansible-moodle
  become: yes
  tasks:
    - name: Führe Apt Update aus.
      ansible.builtin.apt:
        update_cache: yes
    - name: Installiere MariaDB.
      ansible.builtin.apt:
        pkg:
        - mariadb-server
        - mariadb-client 
  
    #- name: Installiere Apache2
    #  ansible.builtin.shell: apt install apache2 apache2-doc
    #- name: Aktiviere via a2enmod 

        

  
