---
- name: Installier LaMp.
  hosts: ansible-moodle # Ansible-Hosts
  tasks:
      ansible.builtin.shell:
        cmd: sudo apt update && apt upgrade -y
        cmd: sudo apt install mariadb-server mariadb-client -y
        cmd: sudo apt install apache2 apache2-doc -y
  
