---
- name: Installiere Moodle.
  become: yes
  hosts: ansible-moodle # Ansible-Hosts (Ziel für die Erstellung + Download)
  tasks:
    - name: Installiere Git.
      ansible.builtin.apt:
        name: git
    #- name: Erstelle Verzeichnis für Git-Paket.
    #  ansible.builtin.shell: mkdir /home/homa/moodle # Pfad für das Moodle-Repository
    #- name: Klone Moodle von Git.
    #  ansible.builtin.git:
    #    repo: https://github.com/moodle/moodle.git
    #   version: MOODLE_403_STABLE
    #    dest: /home/homa/moodle # Ziel Ordner
    #    clone: yes
    #- name: Stelle php.ini ein.
    #  ansible.builtin.blockinfile:
    #    path: /etc/php/8.2/apache2/php.ini
    #    marker: ";extension=ldap"
    #    insertafter: "ldap"
    #    block: |
    #        extension=mysql.so 
    #        extension=gd.so
    #- name: Bearbeitet Maximal Größe für Upload.
    #  ansible.builtin.lineinfile:
    #    path: /etc/php/8.2/apache2/php.ini
    #    search_string: "upload_max_filesize = 2M"
    #    line: upload_max_filesize = 80M
    #- name: Bearbeitet Maximal Größe für Posts.
    #  ansible.builtin.lineinfile:
    #    path: /etc/php/8.2/apache2/php.ini
    #    search_string: "post_max_size = 8M"
    #    line: post_max_size = 80M
    #- name: Starte Apache2 neu.
    #  ansible.builtin.service:
    #    name: apache2
    #    state: restarted
    #- name: Erstelle Datenbank Passwort für root.
    #  ansible.builtin.shell: mysqladmin -u root password '{{ rootdbpw }}'
    #- name: Erstelle Datenbank für Moodle.
    #  ansible.builtin.shell: mysql -u root -e "CREATE DATABASE moodle CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"; 
    - name: Verschiebe Moodle Inhalt (Moodle -> /var/www/html/moodle)
      ansible.builtin.shell: mv /home/homa/moodle/* /var/www/html/moodle
    - name: Erstelle Verzeichnis Moodledata.
      ansible.builtin.file:
        path: /var/www/html/moodledata
        state: directory
        owner: www-data
        group: www-data
        mode: '755'
