---
- name: Installiere das Feature IIS.
  hosts: ansible-win
  tasks:
    - name: Rolle wird Installiert.
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: true
        include_management_tools: true
      register: win_feature
    
