---
- name: Installiere das Feature IIS.
  hosts: ansible-win
  become: yes
  tasks:
    - name: Rolle wird Installiert.
      ansible.windows.win_feature:
        name: Web-Server
        state: present
      register: hyperv_feature
    - name: Falls nötig wird der Host neugestartet.
      ansible.windows.win_reboot:
      when: hyperv_feature.reboot_required
    
