---
- hosts: ansible-moodle
  become: yes
  tasks:
    - name: Führe Apt Update aus.
      ansible.builtin.apt:
        update_cache: yes
    - name: Installiere MariaDB.
      ansible.builtin.apt:
        pkg:
        - mariadb-server
        - mariadb-client 
    - name: Installiere Apache2.
      ansible.builtin.apt:
        pkg:
        - apache2
        - apache2-doc
    - name: Erstelle und akiviere SSL-Zertifikat.
      ansible.builtin.shell: |
          a2enmod ssl && 
          systemctl restart apache2
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt -nodes -subj "/C=DE/ST=NRW/L=Bochum/O=Moodle Install/OU=Private/CN=192.168.81.145"
    - name: Erstelle conf-Datei für Moodle.
      ansible.builtin.file:
        path: /etc/apache2/sites-available/moodle.conf
        state: touch
    - name: Konfiguiere conf-Datei für Moodle.
      ansible.builtin.blockinfile:
        path: /etc/apache2/sites-available/moodle.conf
        block: |
            <VirtualHost *:443>
              ServerName 192.168.81.145
              DocumentRoot /var/www/moodle

              SSLEngine on
              SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
              SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
            </VirtualHost>
    - name: Ändere Rechte für Webverzeichnis.
      #ansible.builtin.shell: chown www-data:www-data /var/www/moodle
      ansible.builtin.file:
        path: /var/www/moodle
        state: directory
        owner: www-data
        group: www-data
    - name: Aktiviere SSL-Verbindung für Moodle.
      ansible.builtin.shell: a2ensite moodle
    - name: Installiere PHP und PHP-MySQL
      ansible.builtin.apt:
        pkg:
        - php
        - php-mysql
    - name: Erstelle PHP-Info Datei [https://url/test.php].
      ansible.builtin.lineinfile:
        path: /var/www/moodle/test.php
        line: <?php phpinfo(); ?>
        create: yes
    - name: Starte Apache2 neu.
      ansible.builtin.service:
        name: apache2
        state: restarted
    - name: Aktiviere Apache2 Weiterleitung.
      ansible.builtin.shell: a2enmod rewrite
    - name: Bearbeite Default.conf.
      ansible.builtin.blockinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        marker: "#Include conf-available/serve-cgi-bin.conf"
        insertafter: "conf"
        block: |
            RewriteEngine On
            RewriteCond %{HTTPS} !=on
            RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R=301,L]
    - name: Richtige PHP-Module ein.
      ansible.builtin.shell: |
          a2dismod mpm_event && 
          a2enmod mpm_prefork &&
          a2enmod php8.2
    - name: Starte Apache2 neu.
      ansible.builtin.service:
        name: apache2
        state: restarted
