---
# Wichtig es muss vorher in Semaphore die Variable {{ new_pass }} erstellt werden. #
# Das Passwort muss zwischen 8 und 64 Zeichen lang sein und mindestens einen Groß- und Kleinbuchstaben, eine Zahl und ein Symbol (.*+?-) enthalten. #
# Nach der Änderung unbedingt die Cookies von Wazuh löschen #
- hosts: all
  become: yes
  tasks:
    - name: Ändere Passwort.
      ansible.builtin.shell: |
            bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -u admin -p {{ new_pass }};
            echo {{ new_pass }} | filebeat keystore add password --stdin --force
            echo {{ new_pass }} | /usr/share/wazuh-dashboard/bin/opensearch-dashboards-keystore --allow-root add -f --stdin opensearch.password
    - name: Starte Filebeat neu.
      ansible.builtin.shell: service filebeat restart
    - name: Starte Wazuh neu.
      ansible.builtin.shell: |
            service wazuh-dashboard restart;
            service wazuh-manager restart;
            service wazuh-indexer restart
    - name: Richte Filebeat ein.
      ansible.builtin.shell: bash /usr/share/wazuh-indexer/bin/indexer-security-init.sh
    - 
      ansible.builtin.shell: filebeat test output
      register: filebeat
    - name: Zeige Ausgabe.
      debug: var=filebeat
      
            

      
            
