---
- name: Erstelle eine VM anhand einer Vorlage.
  hosts: ansible-win
  vars:
    vhd_path: 'C:\Hyper-V\VMs\VHD'
    vhd_size: '20GB'
    vhd_name: 'vm001.vhdx'
    netadapter_name: 'Ethernet1' # Für Extern meistens 0 
    vswitch_name: 'Privat01'
    vswitch_type: 'Private'
    vm_name: 'VM001'
    vm_ram: '1GB'
    vm_hddtype: 'VHD'
    vm_path: 'C:\Hyper-V\VMs'
    vm_gen: '2'
    vm_sec_boottype: 'MicrosoftUEFICertificateAuthority'
  tasks:
    - name: Erstelle Verzeichnisse für Hyper-V VMs.
      ansible.windows.win_file:
        path: '{{ vhd_path }}'
        state: directory
    - name: Erstelle virtuellen Netzwerkadapter {{ vswitch_name }} ({{ vswitch_type }}).      
      ansible.windows.win_powershell:
        script: |
          New-VMSwitch -Name {{ vswitch_name }} -AllowManagementOS $True -NetAdapterName {{ netadapter_name }};
          Set-VMSwitch {{ vswitch_name }} -SwitchType {{ vswitch_type }}
    - name: Ändere Secure-Boot Vorlage in {{ vm_sec_boottype }}.
      ansible.windows.win_powershell:
        script: | 
           Set-VMFirmware -VMName {{ vm_name }} -SecureBootTemplate {{ vm_sec_boottype }}